### ISSUE TITLE
no "Add Workspace Folder" action 

### ISSUE THREAD

**Issue by InstaJun** [RoboGnome/VS_Code_ROS#4]
My VSCode version is 1.79.2. It seems there is no "Add Workspace Folder" action button at welcome page. So is there any workaround to debug multiple nodes?

**Comment by lzptr** [comment]
Hi @InstaJun,

I just checked, and the option is still there, it's just not mentioned anymore on the landing page.
You can access it through the vs code editor commands.
Just use the shortcut: CTRL+SHIFT+P and type
```
>Workspaces: Add Folder to Workspace
```

and then select the folder containing the node you want to debug

**Comment by InstaJun** [comment]
Hi @lzptr 
Thanks for your reply!  Just as you said, i found it!
